# Generated by Django 4.2.3 on 2023-07-31 17:12

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrowing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borrow_date", models.DateField(auto_now_add=True)),
                (
                    "expected_return_date",
                    models.DateField(
                        help_text="Expected return date must be in range from 1 to 30 days after the borrowing date.",
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.date(2023, 8, 1)
                            ),
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date(2023, 8, 30)
                            ),
                        ],
                    ),
                ),
                (
                    "actual_return_date",
                    models.DateField(
                        help_text="Actual returning date can not be earlier the borrowing date.",
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=datetime.date(2023, 7, 31)
                            )
                        ],
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrowings",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="borrowings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["expected_return_date"],
            },
        ),
    ]
