# Generated by Django 4.2.3 on 2023-07-31 17:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="actual_return_date",
            field=models.DateField(
                blank=True,
                help_text="Actual returning date can not be earlier the borrowing date.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2023, 7, 31)
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(
                help_text="Expected return date must be in range from 1 to 90 days after the borrowing date.",
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2023, 8, 1)
                    ),
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date(2023, 10, 29)
                    ),
                ],
            ),
        ),
    ]
